name: "Manda o código para prod"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: "Deploy"
        run: |
          # Estamos criando um SCRIPT aqui
          git config --global user.email "faabrs.rodrigues@gmail.com"
          git config --global user.name "fab-rodrigs [BOT]"

          git checkout -b deploy
          rm -rf README.md
          rm -rf .github
          echo "Minificar o HTML automaticamente"
          git add .
          git commit -m "DEPLOY NOVO"
          git push origin deploy --force
          node -v